version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build: 
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - 8080:80
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword231231"
      MYSQL_DATABASE: eleave
      MYSQL_USER: useradmin231231
      MYSQL_PASSWORD: passwordadmin231231
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
      