<?php
/* config.php */
return array (
  'version' => '6.0.6',
  'web_title' => 'ระบบลาออนไลน์',
  'web_description' => '',
  'timezone' => 'Asia/Bangkok',
  'member_status' => 
  array (
    0 => 'สมาชิก',
    1 => 'ผู้ดูแลระบบ',
    2 => 'เจ้าหน้าที่',
  ),
  'color_status' => 
  array (
    0 => '#259B24',
    1 => '#FF0000',
    2 => '#0E0EDA',
  ),
  'default_icon' => 'icon-verfied',
  'eleave_file_typies' => 
  array (
    0 => 'jpg',
    1 => 'jpeg',
    2 => 'png',
    3 => 'pdf',
  ),
  'eleave_upload_size' => 2097152,
  'eleave_fiscal_year' => 1,
  'password_key' => '6645817f16207',
  'reversion' => 1719972055,
  'skin' => 'skin/default',
  'show_title_logo' => 0,
  'new_line_title' => 0,
  'header_bg_color' => '#01579B',
  'warpper_bg_color' => '#F9F9F9',
  'content_bg' => '#FFFFFF',
  'header_color' => '#FFFFFF',
  'footer_color' => '#999999',
  'logo_color' => '#FFFFFF',
  'theme_width' => 'default',
  'user_forgot' => 1,
  'user_register' => 1,
  'welcome_email' => 0,
  'demo_mode' => 0,
  'activate_user' => 0,
  'new_members_active' => 1,
  'login_fields' => 
  array (
    0 => 'username',
  ),
  'default_department' => '',
  'facebook_appId' => '',
  'google_client_id' => '',
  'login_message' => '',
  'login_message_style' => 'hidden',
  'login_header_color' => '#FFFFFF',
  'login_footer_color' => '#FFFFFF',
  'login_color' => '#FFFFFF',
  'login_bg_color' => '#01579B',
  'noreply_email' => 'portalnet099@gmail.com',
  'email_charset' => 'utf-8',
  'email_Host' => 'smtp.gmail.com',
  'email_Port' => 587,
  'email_SMTPSecure' => '',
  'email_Username' => 'portalnet099@gmail.com',
  'email_use_phpMailer' => 1,
  'email_SMTPAuth' => 1,
  'email_Password' => 'skdx hxwb rzcu uvha',
  'data_controller' => '',
  'cookie_policy' => 0,
);